# Khai báo danh sách các máy chủ (Servers) chạy Vault
all:
  children:
    vault_servers:
      hosts:
        vault-node-1:
          ansible_host: "192.168.1.11"
          private_ip: "192.168.1.11"
          vault_node_id: vault-node-1
        vault-node-2:
          ansible_host: "192.168.1.12"
          private_ip: "192.168.1.12"
          vault_node_id: vault-node-2
        vault-node-3:
          ansible_host: "192.168.1.13"
          private_ip: "192.168.1.13"
          vault_node_id: vault-node-3

    # Định nghĩa Role logic cho các Node
    # Node 1 sẽ là Leader ban đầu (được init và cấp token)
    vault_init:
      hosts:
        vault-node-1:
    
    # Node 2 và 3 sẽ được join vào Cluster của Node 1
    vault_joiners:
      hosts:
        vault-node-2:
        vault-node-3:
        
  vars:
    ansible_user: "ubuntu"          # <--- Đổi thành user có quyền ssh vào server của bạn
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"  # <--- Đường dẫn tới Private Key (có thể đổi thành ~/.ssh/id_ed25519 nếu dùng key ED25519)
    # ansible_ssh_pass: "YourPassword" # Nếu dùng password thay vì SSH key
